
version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cdc-network  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
      - cdc-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cdc-network
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      networks:
        - cdc-network
networks:
  cdc-network:
    driver: bridge
    
volumes:
  mysql_data:
  redis_data: